version: '3.8'
services:
  nginx-proxy:
    ports:
      - 80:80
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    image: nginxproxy/nginx-proxy

  mydb:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - testdata:/var/lib/postgresql/data
    # profiles:
    #   - debug

  adminer:
    image: adminer
    labels:
      traefik.frontend.auth.basic: admin:$1$I5Kt8BwT$G4y6mBV3xVzyZKUECxqV61
    environment:
      - VIRTUAL_HOST=adminer.vcap.me
    ports:
      - 8080
    # profiles:
    #   - debug

  lunch:
    image: lalyos/lunch:v7
    environment:
      - TITLE=Lunch break
      - COLOR=yellow
      - VIRTUAL_HOST=luncs.vcap.me
    ports:
      - 80

  backend:
    image: cmd.cat/curl/psql/dig
    init: true
    command: sleep 9999
    environment:
      - DBHOST=${DBHOST:-mydb}

  frontend:
    image: lalyos/lunch:v7
    #build: .
    init: true
    environment:
      - VIRTUAL_HOST=front.vcap.me
      - TITLE=${TITLE:-Dev env}
      - COLOR=${COLOR:-lightgreen}
      - BODY=${BODY:-Use TITLE/COLOR and BODY env vars or VAR_FILE}

    ports:
      - 80

volumes:
  testdata: